# reference: https://github.com/executablebooks/github-action-demo/

on:
  push:
    branches:
      - main

name: deploy-book

jobs:
  deploy-book:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set Up Virtual Environment and Install dependencies
        run: |
          sudo apt -y install libproj-dev libgeos-dev pkg-config
          python -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip
          pip install --upgrade pyshp
          pip3 install shapely --no-binary shapely
          export PKG_CONFIG_PATH=/usr/local/bin/pkgconfig
          pip install cartopy
          pip install -r requirements.txt

      # Build the book
      - name: Build the book
        run: |
          source env/bin/activate
          cd notes
          jupyter-book build .
          cd -

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./notes/_build/html
